In [2]:
import numpy as np

In [3]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]


In [4]:
# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

In [5]:
np_baseball

array([180, 215, 210, 210, 188, 176, 209, 200])

In [6]:
# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


In [7]:
#multiplication

np_mult = np_baseball*0.0254

In [8]:
np_mult

array([4.572 , 5.461 , 5.334 , 5.334 , 4.7752, 4.4704, 5.3086, 5.08  ])

In [9]:
#printing some specific elements in the numpy array
np_mult[0]

4.572

In [10]:
np_mult[:5]

array([4.572 , 5.461 , 5.334 , 5.334 , 4.7752])

In [11]:
np_mult[-1]

5.08

In [12]:
len(np_mult)

8

In [13]:
#sorting numpy arrays

In [14]:
sorted(np_mult, reverse = False)

[4.4704, 4.572, 4.7752, 5.08, 5.3086, 5.334, 5.334, 5.460999999999999]

In [15]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

# 2D Numpy arrays

In [16]:
np_2d = np.array([[1.2,3.5,2.5],[12,15,45]])

In [17]:
type(np_2d)

numpy.ndarray

In [18]:
np_2d

array([[ 1.2,  3.5,  2.5],
       [12. , 15. , 45. ]])

In [19]:
np_2d.shape

(2, 3)

In [20]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]


In [21]:
# Create a 2D numpy array from baseball: np_baseball
np_baseball =np.array(baseball)

In [22]:
np_baseball[:5]

array([[180. ,  78.4],
       [215. , 102.7],
       [210. ,  98.5],
       [188. ,  75.2]])

In [23]:
np_baseball[1]

array([215. , 102.7])

In [24]:
type(np_baseball)

numpy.ndarray

In [25]:
np_baseball.shape

(4, 2)

In [26]:
np_baseball[0,1]

78.4

In [27]:
np_baseball[0][1]

78.4

In [28]:
np_baseball[3,1]

75.2

In [29]:
np_baseball[0]

array([180. ,  78.4])

In [30]:
print(np_baseball)

[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]


In [31]:
np_baseball[2,:]

array([210. ,  98.5])

In [32]:
np_baseball[:,1:]

array([[ 78.4],
       [102.7],
       [ 98.5],
       [ 75.2]])

In [33]:
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])


In [34]:
print(np_mat * 2)


[[ 2  4]
 [ 6  8]
 [10 12]]


In [35]:
print(np_mat + np.array([10, 10]))


[[11 12]
 [13 14]
 [15 16]]


In [36]:
np_mat + np_mat

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [37]:
conversion = np.array([0.0254, 0.453592,1])

In [38]:
conversion[0:1]

array([0.0254])

In [43]:
np_baseball


array([[180. ,  78.4],
       [215. , 102.7],
       [210. ,  98.5],
       [188. ,  75.2]])

In [44]:
positions = ['GK', 'M', 'A', 'D']
heights = [191, 184, 185, 180]

In [45]:
np_positions = np.array(positions)


In [46]:
np_heights = np.array(heights)

In [47]:
np_heights

array([191, 184, 185, 180])

In [48]:
np_positions

array(['GK', 'M', 'A', 'D'], dtype='<U2')

In [49]:
gk_heights = np_heights[:,np_positions == 'GK']

IndexError: too many indices for array

In [51]:
together = np.array([heights,positions])

In [52]:
together

array([['191', '184', '185', '180'],
       ['GK', 'M', 'A', 'D']], dtype='<U21')

In [54]:
store = np.array([0,9,0,1])

In [55]:
cost = np.array([82,82,73,73])

In [57]:
np_cols = np.array((store,cost))

In [58]:
np_cols

array([[ 0,  9,  0,  1],
       [82, 82, 73, 73]])

In [59]:
np.column_stack((store,cost))

array([[ 0, 82],
       [ 9, 82],
       [ 0, 73],
       [ 1, 73]])

In [63]:
np.array((store,cost))

array([[ 0,  9,  0,  1],
       [82, 82, 73, 73]])

In [64]:
x=['c','b','c','c','c','a']

In [65]:
x.count('c')

4

In [66]:
p=np.array([9,19,13,16])

In [71]:
p[0]

9

In [72]:
z= 'classification'

In [73]:
z.count('s')

2

In [79]:
z=np.array([[5,9,8],
            [9,0,6]])

In [84]:
z[0:,1:]

array([[9, 8],
       [0, 6]])

In [85]:
q=[8,36,31,41,40,43]

In [87]:
len(q)

6

In [88]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.

