In [1]:
import numpy as np

In [2]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]


In [10]:
# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

In [11]:
np_baseball

array([180, 215, 210, 210, 188, 176, 209, 200])

In [12]:
# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


In [14]:
#multiplication

np_mult = np_baseball*0.0254

In [15]:
np_mult

array([4.572 , 5.461 , 5.334 , 5.334 , 4.7752, 4.4704, 5.3086, 5.08  ])

In [17]:
#printing some specific elements in the numpy array
np_mult[0]

4.572

In [19]:
np_mult[:5]

array([4.572 , 5.461 , 5.334 , 5.334 , 4.7752])

In [20]:
np_mult[-1]

5.08

In [21]:
len(np_mult)

8

In [ ]:
#sorting numpy arrays

In [25]:
sorted(np_mult, reverse = False)

[4.4704, 4.572, 4.7752, 5.08, 5.3086, 5.334, 5.334, 5.460999999999999]

In [26]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])